name: Create new release

on: 
  push:
    tags:
    - 'v*'

jobs:
  create-release:
    name: Create release with artifacts of builds
    runs-on: ubuntu-latest
    needs: [build-customize-websites-extension, build-hide-content-extension, build-train-scraping-extension, build-youtube-extension]
    permissions:
      contents: write
    steps:
    - name: Download customize websites extension chrome
      uses: actions/download-artifact@v4
      with:
        name: customize-websites-extension-chrome
        path: customize-websites-extension-chrome
    - name: Archive customize website extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: customize-websites-extension-chrome
        filename: '../customize-websites-extension-chrome.zip'
    - name: Download customize websites extension firefox
      uses: actions/download-artifact@v4
      with:
        name: customize-websites-extension-firefox
        path: customize-websites-extension-firefox
    - name: Archive customize website extension firefox
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: customize-websites-extension-firefox
        filename: '../customize-websites-extension-firefox.zip'
    - name: Download hide content extension chrome
      uses: actions/download-artifact@v4
      with:
        name: hide-content-extension-chrome
        path: hide-content-extension-chrome
    - name: Archive hide content extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: hide-content-extension-chrome
        filename: '../hide-content-extension-chrome.zip'
    - name: Download hide content extension firefox
      uses: actions/download-artifact@v4
      with:
        name: hide-content-extension-firefox
        path: hide-content-extension-firefox
    - name: Archive hide content extension firefox
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: hide-content-extension-firefox
        filename: '../hide-content-extension-firefox.zip'
    - name: Download train scraping extension
      uses: actions/download-artifact@v4
      with:
        name: train-scraping-extension
        path: train-scraping-extension
    - name: Archive train scraping extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: train-scraping-extension/chrome
        filename: '../../train-scraping-extension-chrome.zip'
    - name: Move train scraping extension firefox
      run: |
        mv train-scraping-extension/firefox.xpi ./train-scraping-extension-firefox.xpi
    - name: Download youtube extension
      uses: actions/download-artifact@v4
      with:
        name: youtube-extension
        path: youtube-extension
    - name: Archive youtube extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: youtube-extension/chrome
        filename: '../../youtube-extension-chrome.zip'
    - name: Move youtube extension firefox
      run: |
        mv youtube-extension/firefox.xpi ./youtube-extension-firefox.xpi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,*.xpi"

  build-customize-websites-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Build chrome
      run: |
        cp -r customizeWebsitesExtension customizeWebsitesExtensionChrome
        cd customizeWebsitesExtensionChrome
        node build.js chrome
        rm manifest.src.json
    - name: Upload chrome artifacts
      uses: actions/upload-artifact@v4
      with:
        name: customize-websites-extension-chrome
        path: "./customizeWebsitesExtensionChrome"
    - name: Build firefox
      run: |
        cp -r customizeWebsitesExtension customizeWebsitesExtensionFirefox
        cd customizeWebsitesExtensionFirefox
        node build.js firefox
        rm manifest.src.json
    - name: Upload firefox artifacts
      uses: actions/upload-artifact@v4
      with:
        name: customize-websites-extension-firefox
        path: "./customizeWebsitesExtensionFirefox"

  build-hide-content-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Build chrome
      run: |
        cp -r hideContentExtension hideContentExtensionChrome
        cd hideContentExtensionChrome
        node build.js chrome
        rm manifest.src.json
    - name: Upload chrome artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hide-content-extension-chrome
        path: "./hideContentExtensionChrome"
    - name: Build firefox
      run: |
        cp -r hideContentExtension hideContentExtensionFirefox
        cd hideContentExtensionFirefox
        node build.js firefox
        rm manifest.src.json
    - name: Upload firefox artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hide-content-extension-firefox
        path: "./hideContentExtensionFirefox"

  build-train-scraping-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: NPM Install
      run: |
        cd trainScrapingExtension
        npm install
    - name: Package
      run: |
        cd trainScrapingExtension
        npm run package
        mkdir artifact
        cp -r dist artifact/chrome
    - name: Sign firefox
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        cd trainScrapingExtension/dist
        npx web-ext sign --channel=unlisted
        mv $(find ./web-ext-artifacts -name "*.xpi" -type f) "../artifact/firefox.xpi"
    - name: Upload Artifacts firefox
      uses: actions/upload-artifact@v4
      with:
        name: train-scraping-extension
        path: "./trainScrapingExtension/artifact"

  build-youtube-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: NPM Install
      run: |
        cd youTubeExtension
        npm install
    - name: Package chrome
      run: |
        cd youTubeExtension
        npm run package:chrome
        mkdir artifact
        cp -r dist artifact/chrome
    - name: Package firefox
      run: |
        cd youTubeExtension
        npm run package:firefox
    - name: Sign firefox
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        cd youTubeExtension/dist
        npx web-ext sign --channel=unlisted
        mv $(find ./web-ext-artifacts -name "*.xpi" -type f) "../artifact/firefox.xpi"
    - name: Upload Artifacts firefox
      uses: actions/upload-artifact@v4
      with:
        name: youtube-extension
        path: "./youTubeExtension/artifact"
