name: Create new release of train scraping extension

on: 
  push:
    tags:
    - 'train-scraping-v*'

jobs:
  build-train-scraping-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: NPM Install
      run: |
        cd trainScrapingExtension
        npm install
    - name: Package
      run: |
        cd trainScrapingExtension
        npm run package
        mkdir artifact
        cp -r dist artifact/chrome
    - name: Sign firefox
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        cd trainScrapingExtension/dist
        npx web-ext sign --channel=unlisted
        mv $(find ./web-ext-artifacts -name "*.xpi" -type f) "../artifact/firefox.xpi"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: train-scraping-extension
        path: "./trainScrapingExtension/artifact"

  create-release:
    name: Create release with artifacts of builds
    runs-on: ubuntu-latest
    needs: [build-train-scraping-extension]
    permissions:
      contents: write
    steps:
    - name: Download train scraping extension
      uses: actions/download-artifact@v4
      with:
        name: train-scraping-extension
        path: train-scraping-extension
    - name: Archive train scraping extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: train-scraping-extension/chrome
        filename: '../../train-scraping-extension-chrome.zip'
    - name: Move train scraping extension firefox
      run: |
        mv train-scraping-extension/firefox.xpi ./train-scraping-extension-firefox.xpi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,*.xpi"
