name: Create new release of customize websites extension

on: 
  push:
    tags:
    - 'customize-websites-v*'

jobs:
  build-customize-websites-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build chrome
      run: |
        mkdir artifact
        cp -r customizeWebsitesExtension dist-chrome
        cd dist-chrome
        node adjustManifest.js chrome
        rm manifest.src.json
        rm adjustManifest.js
        
        cp -r . ../artifact/chrome
    - name: Build firefox
      run: |
        cp -r customizeWebsitesExtension dist-firefox
        cd dist-firefox
        node adjustManifest.js firefox
        rm manifest.src.json
        rm adjustManifest.js
    - name: Sign firefox
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        cd dist-firefox
        npm install -g web-ext
        web-ext sign --channel=unlisted
        mv $(find ./web-ext-artifacts -name "*.xpi" -type f) "../artifact/firefox.xpi"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: customize-websites-extension
        path: "./artifact"

  create-release:
    name: Create release with artifacts of builds
    runs-on: ubuntu-latest
    needs: [build-customize-websites-extension]
    permissions:
      contents: write
    steps:
    - name: Download customize websites extension
      uses: actions/download-artifact@v4
      with:
        name: customize-websites-extension
        path: customize-websites-extension
    - name: Archive customize website extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: customize-websites-extension/chrome
        filename: '../../customize-websites-extension-chrome.zip'
    - name: Move customize website extension firefox
      run: |
        mv customize-websites-extension/firefox.xpi ./customize-websites-extension-firefox.xpi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,*.xpi"
