name: Create tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag without prefix (e.g.: 1.0.0)'
        required: true
        type: string

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: Bump customize webistes extension version
      run: |
        cd customizeWebsitesExtension
        cp manifest.src.json manifest.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" manifest.json > manifest.src.json
    - name: Bump hide content extension version
      run: |
        cd hideContentExtension
        cp manifest.src.json manifest.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" manifest.json > manifest.src.json
    - name: Bump train scraping extension version
      run: |
        cd trainScrapingExtension
        
        cp package.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > package.json
        
        cp package-lock.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > package-lock.json
        rm tmp.json

        cd static
        cp manifest.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > manifest.json
        rm tmp.json
    - name: Bump youtube extension version
      run: |
        cd youTubeExtension
        
        cp package.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > package.json
        
        cp package-lock.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > package-lock.json
        rm tmp.json

        cd static
        cp manifest.json tmp.json
        jq '.version = $version' --arg version "${{ github.event.inputs.tag }}" tmp.json > manifest.json
        rm tmp.json
    - name: Commit & Push
      run: |
        git config --global user.name "${{ github.actor }}"
        git commit -am "Bump version to v${{ github.event.inputs.tag }}"
        git push origin

        git tag v${{ github.event.inputs.tag }}
        git push origin --tags