name: Create new release of hide content extension

on: 
  push:
    tags:
    - 'hide-content-v*'

jobs:
  build-hide-content-extension:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Build chrome
      run: |
        mkdir artifact
        cp -r hideContentExtension dist-chrome
        cd dist-chrome
        node adjustManifest.js chrome
        rm manifest.src.json
        rm adjustManifest.js

        cp -r . ../artifact/chrome
    - name: Build firefox
      run: |
        cp -r hideContentExtension dist-firefox
        cd dist-firefox
        node adjustManifest.js firefox
        rm manifest.src.json
        rm adjustManifest.js
    - name: Sign firefox
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        cd dist-firefox
        npm install -g web-ext
        web-ext sign --channel=unlisted
        mv $(find ./web-ext-artifacts -name "*.xpi" -type f) "../artifact/firefox.xpi"
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: hide-content-extension
        path: "./artifact"

  create-release:
    name: Create release with artifacts of builds
    runs-on: ubuntu-latest
    needs: [build-hide-content-extension]
    permissions:
      contents: write
    steps:
    - name: Download hide content extension
      uses: actions/download-artifact@v4
      with:
        name: hide-content-extension
        path: hide-content-extension
    - name: Archive hide content extension chrome
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: hide-content-extension/chrome
        filename: '../../hide-content-extension-chrome.zip'
    - name: Move hide content extension firefox
      run: |
        mv hide-content-extension/firefox.xpi ./hide-content-extension-firefox.xpi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip,*.xpi"
