name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release-youtube-extension:
    name: Release static files of youtube extension to GitHub Releases
    runs-on: ubuntu-latest
    needs: build-youtube-extension
    steps:
      - name: Download youtube extension
        uses: actions/download-artifact@v2
        with:
          name: build-youtube-extension
      - name: Archive extension
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'youtube-extension.zip'
      - name: Create youtube extension GitHub Release
        id: create-youtube-extension-auto-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.auto.${{ github.run_number }}
          release_name: YouTube Extension automatic Release v2.auto.${{ github.run_number }}
          prerelease: true
      - name: Upload youtube extensions assets to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-youtube-extension-auto-release.outputs.upload_url }}
          asset_path: ./youtube-extension.zip
          asset_name: youtube-extension-v2-auto-${{ github.run_number }}.zip
          asset_content_type: application/zip

  build-youtube-extension:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '20'

    - name: Build
      run: |
        cd youTubeExtension
        npm install
        npm run package
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-youtube-extension
        path: "./youTubeExtension/dist"
